name: easy_locale
description: "Easy localization & internationalization (i18n) library."
version: 0.0.12
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  devicelocale: ^0.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_locale
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - locale
  - i18n
  - localization
  - internationalization
  - easy-packages
